/**
 * Temporary prototype data.
 * Replace with API data when backend integration begins.
 */

import { AuditRequest } from "../types/audit-center";

export const auditRequests: AuditRequest[] = [
  {
    id: "AUDIT-2026-0001",
    title: "智能客服 Skill 发布申请",
    type: "capability_publish",
    capabilityName: "智能海外回复助手",
    capabilityType: "Skill",
    version: "v1.0.0",
    applicant: "李娜 (Lina)",
    applicantEmail: "lina.li@haze-tech.com",
    department: "客户服务部",
    submitTime: "2026-06-15 09:30",
    urgency: "normal",
    status: "pending",
    timeLeft: "剩余 24 小时",
    description: "发布面向海外消费者的智能语义回复与情感分析客服助理 Skill，旨在提升工单初次回复效率和满意度。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0002",
    title: "财务报表分析 MCP Server 发布申请",
    type: "capability_publish",
    capabilityName: "财务分析数据服务端",
    capabilityType: "MCP Server",
    version: "v1.2.0",
    applicant: "张杰 (Jack)",
    applicantEmail: "jack.zhang@haze-tech.com",
    department: "财务管理部",
    submitTime: "2026-06-15 11:20",
    urgency: "urgent",
    status: "processing",
    timeLeft: "剩余 12 小时",
    description: "提供标准报表抓取与多因子分析 MCP 协议服务端接口，支持多账套合并报表的数据分析和检索。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0003",
    title: "法务合同校验 Tool 发布申请",
    type: "capability_publish",
    capabilityName: "合同违规项自动批改",
    capabilityType: "MCP Tool",
    version: "v1.0.2",
    applicant: "王磊 (Leo)",
    applicantEmail: "leo.wang@haze-tech.com",
    department: "法务合规部",
    submitTime: "2026-06-15 14:00",
    urgency: "critical",
    status: "pending",
    timeLeft: "剩余 3 小时",
    description: "自动合规条款校验与高风险项警告，该 Tool 支持对写入的合同文本附件进行原地标注和高亮。",
    hasBlocker: true,
    blockReason: "安全扫描未通过：检测到代码中存在疑似临时加密系统的私钥泄露风险"
  },
  {
    id: "AUDIT-2026-0004",
    title: "商品推荐引擎 Skill 升级发布",
    type: "capability_publish",
    capabilityName: "海外商品个性化推荐",
    capabilityType: "Skill",
    version: "v2.1.0",
    applicant: "陈静 (Jane)",
    applicantEmail: "jane.chen@haze-tech.com",
    department: "市场营销部",
    submitTime: "2026-06-14 10:15",
    urgency: "normal",
    status: "pending",
    timeLeft: "剩余 2 天",
    description: "经过多轮 A/B 测试，最新版发布将个性化召回比例提高 15%，增强了对本地节日大促场景的多模态分析。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0005",
    title: "核心财务数据看板访问权限申请",
    type: "permission_request",
    capabilityName: "财务风控大盘",
    capabilityType: "Skill",
    applicant: "刘洋 (Alex)",
    applicantEmail: "alex.liu@haze-tech.com",
    department: "运营部",
    submitTime: "2026-06-15 15:45",
    urgency: "urgent",
    status: "pending",
    timeLeft: "剩余 15 小时",
    description: "申请访问财务风控核心大盘 Skill 权限，包含各个业务线实时流转情况，由于需要季度运营审计汇报需要使用。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0006",
    title: "系统异常提取 MCP Server 访问权限申请",
    type: "permission_request",
    capabilityName: "ElasticSearch 检索中枢",
    capabilityType: "MCP Server",
    applicant: "杨波 (Bob)",
    applicantEmail: "bob.yang@haze-tech.com",
    department: "安全审计组",
    submitTime: "2026-06-14 16:30",
    urgency: "normal",
    status: "processing",
    timeLeft: "剩余 36 小时",
    description: "生产异常日志调阅及快速审计所需的 ES MCP Server 接入授权，需要查看部分脱敏的用户操作链路由。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0007",
    title: "生产数据库删除表格 Tool 调用权限申请",
    type: "permission_request",
    capabilityName: "临时报表物理清除工具",
    capabilityType: "MCP Tool",
    applicant: "高阳 (Gary)",
    applicantEmail: "gary.gao@haze-tech.com",
    department: "系统运维部",
    submitTime: "2026-06-15 19:20",
    urgency: "critical",
    status: "pending",
    timeLeft: "剩余 1 小时",
    description: "申请在自动化运维排期中使用清扫临时表物理只写 API 的权限，需要彻底释放过期磁盘空间。",
    hasBlocker: true,
    blockReason: "安全架构警报：该 Tool 的行为属于破坏性 DDL 删除，且其声明的权限策略中未包含人工二次确认节点。"
  },
  {
    id: "AUDIT-2026-0008",
    title: "运维系统一键清空 Redis 缓存 Tool 即时执行申请",
    type: "high_risk_tool",
    capabilityName: "Redis单节点全面刷新",
    capabilityType: "MCP Tool",
    applicant: "邓超 (Dawn)",
    applicantEmail: "dawn.deng@haze-tech.com",
    department: "系统运维部",
    submitTime: "2026-06-15 20:10",
    urgency: "critical",
    status: "pending",
    timeLeft: "剩余 2 小时",
    description: "在 Staging 环境中执行特定 Redis 节点的 FlushAll 数据清零，以修复缓存污染导致的网络同步卡顿问题。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0009",
    title: "财务库批量导出转账流水 Tool 即时执行申请",
    type: "high_risk_tool",
    capabilityName: "大额收付资金打包装盘",
    capabilityType: "MCP Tool",
    applicant: "周星 (Stephen)",
    applicantEmail: "stephen.zhou@haze-tech.com",
    department: "财务管理部",
    submitTime: "2026-06-15 18:22",
    urgency: "urgent",
    status: "processing",
    timeLeft: "剩余 5 小时",
    description: "批量打包并发送包含银行明细在内的 2026 年二季度出入资金大额对账单。涉及多处机密脱敏规则，属最高风险级操作。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0010",
    title: "招聘漏斗自动分析 Skill 版本更新审核",
    type: "version_publish",
    capabilityName: "HR招聘全景助手",
    capabilityType: "Skill",
    version: "v1.5.0",
    targetVersion: "v1.6.0",
    applicant: "王磊 (Leo)",
    applicantEmail: "leo.wang@haze-tech.com",
    department: "人力资源部",
    submitTime: "2026-06-14 09:12",
    urgency: "normal",
    status: "pending",
    timeLeft: "剩余 1 天",
    description: "支持从更多主流招聘网站的数据抽取，并在模型指令逻辑里增加了候选人匹配度自适应评判标准。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0011",
    title: "电商订单抓取 MCP Server 核心版本升级",
    type: "version_publish",
    capabilityName: "通用电商同步适配器",
    capabilityType: "MCP Server",
    version: "v2.0.1",
    targetVersion: "v2.1.0",
    applicant: "陈静 (Jane)",
    applicantEmail: "jane.chen@haze-tech.com",
    department: "技术研发部",
    submitTime: "2026-06-15 17:40",
    urgency: "urgent",
    status: "pending",
    timeLeft: "剩余 8 小时",
    description: "升级底层网络并发库，增加了重试机制并全面支持新版电商后台 API，变更涉及新的参数字段 `delivery_channel` 声明。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0012",
    title: "废弃低效发票 OCR Tool 下线申请",
    type: "capability_offline",
    capabilityName: "发票扫描OCR接口",
    capabilityType: "MCP Tool",
    applicant: "张杰 (Jack)",
    applicantEmail: "jack.zhang@haze-tech.com",
    department: "财务管理部",
    submitTime: "2026-06-13 14:10",
    urgency: "normal",
    status: "pending",
    timeLeft: "剩余 3 天",
    description: "该旧版发票扫描插件已由全新的高精度多模态发票核验 Skill 全面替代，现申请下线此单项接口，降低安全暴露面。",
    hasBlocker: false
  },

  // Finished / History Items for complete records coverage (approved, rejected, withdrawn, expired)
  {
    id: "AUDIT-2026-0013",
    title: "智能公文起草助手 发布审核",
    type: "capability_publish",
    capabilityName: "行政公文规整小助手",
    capabilityType: "Skill",
    version: "v1.0.0",
    applicant: "孙强 (Sunny)",
    applicantEmail: "sunny.sun@haze-tech.com",
    department: "行政总经理办公室",
    submitTime: "2026-06-12 10:00",
    urgency: "normal",
    status: "approved",
    timeLeft: "已归档",
    description: "自动撰写符合公章申报和规范的行政公文，已完成审核并通过安全沙箱检查。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0014",
    title: "数据库自动化分析 MCP Server 接入权限申请",
    type: "permission_request",
    capabilityName: "关系型数据库运维中枢",
    capabilityType: "MCP Server",
    applicant: "高阳 (Gary)",
    applicantEmail: "gary.gao@haze-tech.com",
    department: "系统运维部",
    submitTime: "2026-06-11 11:00",
    urgency: "urgent",
    status: "rejected",
    timeLeft: "已归档",
    description: "申请免密读写直接操控生产库元数据，由于权限请求范围过于宽泛且未绑定具体操作名，已被安全合规退回。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0015",
    title: "企业微信群发 API 即时执行申请",
    type: "high_risk_tool",
    capabilityName: "企业核心通知群派发",
    capabilityType: "MCP Tool",
    applicant: "陈静 (Jane)",
    applicantEmail: "jane.chen@haze-tech.com",
    department: "市场营销部",
    submitTime: "2026-06-10 12:00",
    urgency: "normal",
    status: "withdrawn",
    timeLeft: "已归档",
    description: "市场营销群发活动公告，由于文案需进一步调整，申请人已主动在工作区撤回此单申请。",
    hasBlocker: false
  },
  {
    id: "AUDIT-2026-0016",
    title: "过期用户数据擦除 Tool 即时执行申请",
    type: "high_risk_tool",
    capabilityName: "死账户全生命清理",
    capabilityType: "MCP Tool",
    applicant: "杨波 (Bob)",
    applicantEmail: "bob.yang@haze-tech.com",
    department: "安全审计组",
    submitTime: "2026-06-08 09:00",
    urgency: "urgent",
    status: "expired",
    timeLeft: "已超时 32 小时",
    description: "按照 72 小时限时清理的过期用户物理销户 Tool 调用，由于多重审批到期前审核人仍未反馈，系统自动判定为超时过期。",
    hasBlocker: false
  }
];
