import { CapabilityItem } from "../types/capability";

export const MOCK_MARKETPLACE_SKILLS: CapabilityItem[] = [
  {
    id: "sk_1",
    name: "销售日报自动分析",
    type: "Skill",
    description: "汇聚并自动分析前一日全渠道销售数据，自动产出包含异动归因、趋势预测、高潜货品及爆款建议的结构化日报。",
    calls: 1248,
    status: "active",
    author: "数据科学部",
    version: "v2.1.0",
    updateTime: "2026-06-12",
    permissionsStatus: "direct",
    riskLevel: "low",
    department: "数据科学部",
    tags: ["数据分析", "电商运营", "自动化"],
    scenarios: ["主站每日销售分析", "大促业绩跟踪", "异常销售归因"],
    whatItCanDo: ["提炼多维度销售核心指标与同比变动", "识别非正常下滑/暴涨品类并做下钻归因", "生成图表和排版考究的 Markdown 销售简报"],
    whatItCantDo: ["无法关联未在ERP登记的其他销售渠道数据", "不负责实际执行降价或促量修改指令"],
    inputExample: "请分析2026年6月14日华东区女装品类日报，销售额500万，退货率高达15%。",
    outputExample: "### 华东区女装品类日报分析报告\n\n**核心结论：** 6月14日销售额环比下滑4.2%，但退货率达15%（触发红色预警）。\n\n**归因分析：** 退货率激增主要来源于 `sk-1029` 连衣裙（退货率34%），用户反馈其尺码严重偏小。",
    steps: ["输入分析日期与核心指标", "大模型调用ERP模型提取多因子属性", "完成多因子交叉比对算法生成报告"],
    examples: ["分析昨日跨境电商服饰类目表现", "诊断本周数码配件退货率异常升高的原因"],
    notes: ["建议配合企業数据中心 MCP 获取精准元数据", "分析时请注意保证本地区服划分与账期口径一致"],
    dependencies: [
      { type: "MCP Server", name: "企业数据中心 MCP" }
    ],
    isFavorite: true
  },
  {
    id: "sk_2",
    name: "企业知识检索助手",
    type: "Skill",
    description: "一站式极速检索、提炼企业所有历史规章制度、福利标准、技术红皮书，安全防泄露，带有溯源引用。",
    calls: 5410,
    status: "active",
    author: "信息安全部",
    version: "v4.0.2",
    updateTime: "2026-06-14",
    permissionsStatus: "granted",
    riskLevel: "low",
    department: "行政与安全部",
    tags: ["知识检索", "企业办公", "行政制度"],
    scenarios: ["新员工入职导引培训", "公司最新财务与差旅规程核实", "IT技术栈架构查阅"],
    whatItCanDo: ["在万级文档库中执行向量交叉检索", "提供带有原文段落和引用文件出处的答复", "自动总结规章相似点，去重合并"],
    whatItCantDo: ["不能查阅标有机密安全级别的高敏感未授权机要公文", "不支持外部公共网络搜索引擎搜索"],
    inputExample: "北京分公司的差旅住宿标准是多少？有餐补吗？",
    outputExample: "依据《2026企业差旅管理标准第四版》，北京分公司普通员工住宿标准为 500元/天。提供出差期间 80元/天 的餐费补助，无需发票凭证。",
    steps: ["在对话框中输入行政人事相关疑问", "系统自动解析疑问并进行向量检索", "大模型合成有来源的政策说明文档"],
    examples: ["年假调休有过期说吗？", "如何报销办公电脑损耗？"],
    notes: ["各分公司细则不同，若未指明城市，系统默认基于集团总部一般标准回复"],
    dependencies: [],
    isFavorite: false
  },
  {
    id: "sk_3",
    name: "行业研报深度分析",
    type: "Skill",
    description: "提供金融级、逻辑闭环的深度分析能力。快速剖析数十万字多格式券商、机构研报，自动绘制商业画布与竞对矩阵。",
    calls: 890,
    status: "active",
    author: "战略规划部",
    version: "v1.2.0",
    updateTime: "2026-06-11",
    permissionsStatus: "need_apply",
    riskLevel: "medium",
    department: "战略规划部",
    tags: ["数据分析", "财务", "决策辅助"],
    scenarios: ["前瞻性赛道筛选与可行性论证", "行业核心头部玩家竞争优势拆解", "市场复合增长率(CAGR)预测整理"],
    whatItCanDo: ["自动解析并对比多篇超长 PDF/Docs 格式研究报告", "提炼估值区间、PE模型及主推逻辑核心要点", "自动形成波特五力模型和 SWOT 分析大纲"],
    whatItCantDo: ["无法绝对保证未来财务模型的100%精准度，仅供决策辅助", "不能拉取非上市公司的机密财务账目"],
    inputExample: "深度总结2025年集成电路先进制程及设备国产化替代进程研究报告。",
    outputExample: "**研报摘要：** 我国半导体先进制程在刻蚀、薄膜沉积领域国产化率突破45%，但光刻及量测环节依旧承压。预测2026年复合增长率在18.2%左右。",
    steps: ["上传研报 PDF 附件或提供研报本地路径", "开始向量块深度精读，解析所有图表与数表", "选择商业画布或竞对分析矩阵输出格式"],
    examples: ["如何评价今年新能源储能市场的增速降温？", "对比华为与特斯拉在智能驾驶的硬件选择差异"],
    notes: ["由于本项应用消耗高算力 Token 较多，建议单次研报上传不超过 3 份"],
    dependencies: [],
    isFavorite: true
  }
];
