/**
 * Temporary prototype data.
 * Replace with API data when backend integration begins.
 */
import { SystemAuditLog } from "../types/system-management";

export const systemAuditLogs: SystemAuditLog[] = [
  {
    id: "LOG-0001",
    time: "2026-06-15 20:45:12",
    user: "章建华",
    userId: "U1001",
    department: "企业架构部",
    module: "settings",
    actionType: "修改系统安全策略",
    target: "全局密码与锁定策略",
    targetId: "POL_PASSWORD",
    result: "success",
    ip: "192.168.1.18",
    traceId: "tr-7f000001-f25a-4b2a",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    requestSummary: "POST /api/v1/system/policy/password - minLength=12, historyCount=3",
    beforeData: '{"minLength": 10, "requireNumbers": true, "requireLetters": true, "requireSpecial": false, "historyCount": 2}',
    afterData: '{"minLength": 12, "requireNumbers": true, "requireLetters": true, "requireSpecial": true, "historyCount": 3}',
    errorMsg: ""
  },
  {
    id: "LOG-0002",
    time: "2026-06-15 19:30:44",
    user: "吴海涛",
    userId: "U1005",
    department: "信息安全部",
    module: "user",
    actionType: "禁用平台用户账号",
    target: "赵敏",
    targetId: "U1011",
    result: "success",
    ip: "10.154.2.45",
    traceId: "tr-7f000001-ec41-11b2",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    requestSummary: "PUT /api/v1/system/users/U1011/status - status=disabled, notes=账户安全审计挂起",
    beforeData: '{"status": "active", "notes": "销售部骨干"}',
    afterData: '{"status": "disabled", "notes": "该账号由管理员因业务变动暂时禁用"}',
    errorMsg: ""
  },
  {
    id: "LOG-0003",
    time: "2026-06-15 18:22:10",
    user: "李国强",
    userId: "U1002",
    department: "总裁办",
    module: "auth",
    actionType: "SSO联邦身份校验登录",
    target: "企业 OIDC 网关",
    targetId: "PROV_OIDC",
    result: "success",
    ip: "122.45.1.92",
    traceId: "tr-7f000001-99af-32ef",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X)",
    requestSummary: "GET /api/v1/auth/callback/oidc - code=***, state=***",
    beforeData: "-",
    afterData: '{"loginUser": "liguoqiang@haze.co", "ssoSessionId": "OIDC-98834a"}',
    errorMsg: ""
  },
  {
    id: "LOG-0004",
    time: "2026-06-15 17:15:22",
    user: "陈晓磊",
    userId: "U1003",
    department: "AI 平台研发部",
    module: "developer",
    actionType: "配置物理 MCP 代理总线",
    target: "MySQL Database Schema Analyzer",
    targetId: "MCP-8822",
    result: "success",
    ip: "192.168.1.99",
    traceId: "tr-7f000001-52f1-419b",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/114.0.0.0",
    requestSummary: "POST /api/v1/mcp/register - host=10.0.2.14, port=8080, transport=sse",
    beforeData: "{}",
    afterData: '{"name": "mysql-analyzer-mcp", "endpoint": "http://10.0.2.14:8080/sse", "registeredTools": ["query_schema", "list_tables"]}',
    errorMsg: ""
  },
  {
    id: "LOG-0005",
    time: "2026-06-15 16:58:30",
    user: "何美玲",
    userId: "U1007",
    department: "业务运营组一队",
    module: "audit",
    actionType: "审批通过 Skill 发布上架",
    target: "财务智能数据提取器",
    targetId: "SK-9005",
    result: "success",
    ip: "192.168.3.11",
    traceId: "tr-7f000001-a1b2-c3d4",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "POST /api/v1/audit/releases/SK-9005/approve - comment=符合企业代码开发及隐私要求",
    beforeData: '{"status": "pending_audit"}',
    afterData: '{"status": "published", "activeVersion": "v1.0.0"}',
    errorMsg: ""
  },
  {
    id: "LOG-0006",
    time: "2026-06-15 16:12:00",
    user: "张三丰",
    userId: "U1012",
    department: "客户成功华南群",
    module: "auth",
    actionType: "账号密码登录失败",
    target: "本地账号校验",
    targetId: "PROV_PWD",
    result: "failed",
    ip: "114.23.82.112",
    traceId: "tr-7f000001-09df-22fe",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/113.0.0.0",
    requestSummary: "POST /api/v1/auth/login/password - user=sanfeng@haze.co",
    beforeData: "-",
    afterData: "-",
    errorMsg: "密码验证不正确，剩余尝试次数：2"
  },
  {
    id: "LOG-0007",
    time: "2026-06-15 15:43:00",
    user: "章建华",
    userId: "U1001",
    department: "企业架构部",
    module: "user",
    actionType: "一键重置用户登录密码",
    target: "宋承宪",
    targetId: "U1009",
    result: "success",
    ip: "192.168.1.18",
    traceId: "tr-7f000001-ccad-45ea",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "POST /api/v1/system/users/U1009/reset-password",
    beforeData: "-",
    afterData: '{"status": "password_reset_triggered", "tempPassword": "built-in-secured-ref"}',
    errorMsg: ""
  },
  {
    id: "LOG-0008",
    time: "2026-06-15 14:22:15",
    user: "周梦琪",
    userId: "U1004",
    department: "大模型算法团队",
    module: "market",
    actionType: "申请能力限制调用白名单",
    target: "外部网络研判搜索引擎",
    targetId: "SK-3044",
    result: "success",
    ip: "192.168.1.133",
    traceId: "tr-7f000001-8bda-3a01",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/market/apply - capabilityId=SK-3044, durationDays=90",
    beforeData: "{}",
    afterData: '{"applicationId": "AP-9903", "grantedStatus": "pending_manager_approve"}',
    errorMsg: ""
  },
  {
    id: "LOG-0009",
    time: "2026-06-15 13:00:10",
    user: "宋承宪",
    userId: "U1009",
    department: "应用开发一中心",
    module: "developer",
    actionType: "克隆编辑开发中 Skill",
    target: "合同文本多点比对工具 Component",
    targetId: "SK-1120",
    result: "success",
    ip: "192.168.5.54",
    traceId: "tr-7f000001-4fea-019d",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/developer/skills/SK-1120 - systemPrompt=Refined system regulatory scope",
    beforeData: '{"systemPrompt": "对比两份合同的格式差异"}',
    afterData: '{"systemPrompt": "对比两份合同的格式差异，并基于2026民法典草案校验合规漏洞"}',
    errorMsg: ""
  },
  {
    id: "LOG-0010",
    time: "2026-06-15 11:45:00",
    user: "吴海涛",
    userId: "U1005",
    department: "信息安全部",
    module: "settings",
    actionType: "更新 MCP 实体访问白名单",
    target: "安全防火墙网卡段配置",
    targetId: "POL_IP_WHITE",
    result: "success",
    ip: "10.154.2.45",
    traceId: "tr-7f000001-22ad-fa3c",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "PUT /api/v1/system/policy/network - mcpServerWhitelist",
    beforeData: '"localhost, 127.0.0.1, 10.0.0.0/8"',
    afterData: '"localhost, 127.0.0.1, 10.0.0.0/8, *.haze.co, *.haze-corp.com"',
    errorMsg: ""
  },
  {
    id: "LOG-0011",
    time: "2026-06-15 10:30:12",
    user: "郭亮",
    userId: "U1006",
    department: "业务运营组一队",
    module: "audit",
    actionType: "驳回能力发布申请 (内容风险)",
    target: "员工非合规情绪分析 Skill",
    targetId: "SK-9011",
    result: "rejected",
    ip: "192.168.3.18",
    traceId: "tr-7f000001-7fa1-e234",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/audit/releases/SK-9011/reject - comment=涉及监控员工隐私及情绪敏感词汇，不予批准",
    beforeData: '{"status": "pending_audit"}',
    afterData: '{"status": "rejected", "comment": "涉及监控员工隐私及情绪敏感词汇"}',
    errorMsg: ""
  },
  {
    id: "LOG-0012",
    time: "2026-06-15 09:12:30",
    user: "刘婷婷",
    userId: "U1016",
    department: "人力资源综合部",
    module: "user",
    actionType: "创建组织内新用户账号",
    target: "张三丰",
    targetId: "U1012",
    result: "success",
    ip: "192.168.4.10",
    traceId: "tr-7f000001-9a2c-e1fc",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/system/users - name=张三丰, email=sanfeng@haze.co, userType=collaborator",
    beforeData: "{}",
    afterData: '{"id": "U1012", "name": "张三丰", "email": "sanfeng@haze.co", "status": "pending"}',
    errorMsg: ""
  },
  {
    id: "LOG-0013",
    time: "2026-06-14 18:22:15",
    user: "章建华",
    userId: "U1001",
    department: "企业架构部",
    module: "role",
    actionType: "新增自定义权限角色",
    target: "只读运营观察员",
    targetId: "R204",
    result: "success",
    ip: "192.168.1.18",
    traceId: "tr-7f000001-feca-4bde",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "POST /api/v1/system/roles - name=只读运营观察员, code=READONLY_OBSERVER",
    beforeData: "{}",
    afterData: '{"id": "R204", "name": "只读运营观察员", "code": "READONLY_OBSERVER", "permissionCount": 5}',
    errorMsg: ""
  },
  {
    id: "LOG-0014",
    time: "2026-06-14 15:35:10",
    user: "沈腾",
    userId: "U1019",
    department: "业务运营组一队",
    module: "market",
    actionType: "运行调用第三方翻译引擎",
    target: "多国语言高级润色 Skill",
    targetId: "SK-2041",
    result: "success",
    ip: "192.168.3.118",
    traceId: "tr-7f000001-0bc3-aa2d",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/market/skills/SK-2041/run - params={'text': 'Hello world'}",
    beforeData: "-",
    afterData: '{"callsCount": 44, "status": "ok"}',
    errorMsg: ""
  },
  {
    id: "LOG-0015",
    time: "2026-06-14 11:40:55",
    user: "刘向东",
    userId: "U1010",
    department: "企业架构部",
    module: "user",
    actionType: "修改分配用户角色映射",
    target: "周杰",
    targetId: "U1017",
    result: "success",
    ip: "192.168.1.55",
    traceId: "tr-7f000001-bc8a-d9f2",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "PUT /api/v1/system/users/U1017/roles - roles=['CAPABILITY_DEVELOPER']",
    beforeData: '{"roles": ["NORMAL_USER"]}',
    afterData: '{"roles": ["CAPABILITY_DEVELOPER"]}',
    errorMsg: ""
  },
  {
    id: "LOG-0016",
    time: "2026-06-14 09:30:15",
    user: "周梦琪",
    userId: "U1004",
    department: "大模型算法团队",
    module: "developer",
    actionType: "删除作废测试开发中 Skill",
    target: "测试用垃圾大模型微调 Tool",
    targetId: "SK-8092",
    result: "success",
    ip: "192.168.1.134",
    traceId: "tr-7f000001-e23a-f3bc",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "DELETE /api/v1/developer/skills/SK-8092",
    beforeData: '{"name": "测试垃圾工具"}',
    afterData: "{}",
    errorMsg: ""
  },
  {
    id: "LOG-0017",
    time: "2026-06-13 17:30:10",
    user: "王小明",
    userId: "U1008",
    department: "应用开发一中心",
    module: "auth",
    actionType: "密码安全登录平台",
    target: "本地账号密码验证",
    targetId: "PROV_PWD",
    result: "success",
    ip: "114.23.82.122",
    traceId: "tr-7f000001-2134-abcf",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/114.0.0.0",
    requestSummary: "POST /api/v1/auth/login/password - user=wangxiaoming@haze.co",
    beforeData: "-",
    afterData: '{"loginUser": "wangxiaoming@haze.co"}',
    errorMsg: ""
  },
  {
    id: "LOG-0018",
    time: "2026-06-13 14:12:00",
    user: "陈晓磊",
    userId: "U1003",
    department: "AI 平台研发部",
    module: "monitor",
    actionType: "触发手动 MCP 运行健康诊断",
    target: "Redis Cluster Manager Server",
    targetId: "SRV-2015",
    result: "success",
    ip: "192.168.1.99",
    traceId: "tr-7f000001-ddcf-11ef",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "POST /api/v1/monitor/services/SRV-2015/diagnose",
    beforeData: '{"health": "degraded"}',
    afterData: '{"health": "healthy", "latency": "12ms", "nodesUp": 5}',
    errorMsg: ""
  },
  {
    id: "LOG-0019",
    time: "2026-06-13 10:20:11",
    user: "林丹",
    userId: "U1018",
    department: "大模型算法团队",
    module: "market",
    actionType: "执行运行中台归档 Tool",
    target: "中台业务日报批量分析助手",
    targetId: "SK-4903",
    result: "success",
    ip: "192.168.1.140",
    traceId: "tr-7f000001-9a1b-cce1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/market/skills/SK-4903/run - params={'date': '2026-06-12'}",
    beforeData: "-",
    afterData: '{"summaryReportUrl": "https://haze-corp.com/out/report.pdf"}',
    errorMsg: ""
  },
  {
    id: "LOG-0020",
    time: "2026-06-12 16:35:10",
    user: "高圆圆",
    userId: "U1020",
    department: "销售支持组团队",
    module: "market",
    actionType: "查看能力特定敏感日志",
    target: "客户特定CRM对接网关",
    targetId: "SK-5120",
    result: "rejected",
    ip: "192.168.3.155",
    traceId: "tr-7f000001-bbcf-e3fa",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "GET /api/v1/monitor/logs?targetId=SK-5120&level=error",
    beforeData: "-",
    afterData: "-",
    errorMsg: "权限不足，获取敏感 CRM 链路操作日志请求已被安全审计系统拦截"
  },
  {
    id: "LOG-0021",
    time: "2026-06-12 11:00:44",
    user: "周杰",
    userId: "U1017",
    department: "AI 平台研发部",
    module: "developer",
    actionType: "更新 MCP 元参数模型",
    target: "RAG 嵌入多路召回服务",
    targetId: "MCP-8800",
    result: "success",
    ip: "192.168.1.101",
    traceId: "tr-7f000001-ee0a-31b2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/developer/mcp/MCP-8800/parameters - model=gemini-2.5-pro",
    beforeData: '{"model": "gemini-1.5-flash"}',
    afterData: '{"model": "gemini-2.5-pro"}',
    errorMsg: ""
  },
  {
    id: "LOG-0022",
    time: "2026-06-12 08:33:14",
    user: "李四光",
    userId: "U1013",
    department: "资源池研发支撑",
    module: "auth",
    actionType: "登录密码重置校验",
    target: "本地账号密码重置",
    targetId: "PROV_PWD",
    result: "success",
    ip: "192.168.6.211",
    traceId: "tr-7f000001-09fa-e3df",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/auth/reset-verify?ticket=*** - user=siguang@haze.co",
    beforeData: "-",
    afterData: '{"status": "password_successfully_updated"}',
    errorMsg: ""
  },
  {
    id: "LOG-0023",
    time: "2026-06-11 15:40:00",
    user: "何美玲",
    userId: "U1007",
    department: "业务运营组一队",
    module: "user",
    actionType: "修改组织架构部门映射",
    target: "应用开发一中心",
    targetId: "D106",
    result: "success",
    ip: "192.168.3.11",
    traceId: "tr-7f000001-71fb-99e2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/system/departments/D106 - parentId=D101",
    beforeData: '{"parentId": "D100"}',
    afterData: '{"parentId": "D101"}',
    errorMsg: ""
  },
  {
    id: "LOG-0024",
    time: "2026-06-11 11:22:00",
    user: "章建华",
    userId: "U1001",
    department: "企业架构部",
    module: "settings",
    actionType: "修改审计日志输出通道",
    target: "审计通道脱敏配置",
    targetId: "POL_AUDIT_DESENSITIZE",
    result: "success",
    ip: "192.168.1.18",
    traceId: "tr-7f000001-abce-521a",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/system/policy/audit - maskSensitiveFields=true",
    beforeData: '{"maskSensitiveFields": false}',
    afterData: '{"maskSensitiveFields": true, "maskedKeys": ["password", "secret", "token", "apiKey"]}',
    errorMsg: ""
  },
  {
    id: "LOG-0025",
    time: "2026-06-11 09:15:00",
    user: "吴海涛",
    userId: "U1005",
    department: "信息安全部",
    module: "role",
    actionType: "复制克隆权限角色",
    target: "Custom 安全审计师 (Clone)",
    targetId: "R203",
    result: "success",
    ip: "10.154.2.45",
    traceId: "tr-7f000001-ecdf-10fe",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/system/roles/R203/clone?newName=测试审计专员&newCode=TEST_AUDIT_SPECIALIST",
    beforeData: "{}",
    afterData: '{"id": "R203_clone", "name": "测试审计专员", "code": "TEST_AUDIT_SPECIALIST"}',
    errorMsg: ""
  },
  {
    id: "LOG-0026",
    time: "2026-06-10 14:00:00",
    user: "李国强",
    userId: "U1002",
    department: "总裁办",
    module: "settings",
    actionType: "修改全局 OIDC 端点",
    target: "Auth SSO Config Center",
    targetId: "PROV_OIDC",
    result: "success",
    ip: "122.45.1.92",
    traceId: "tr-7f000001-bc81-aa12",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/system/auth/PROV_OIDC - scopes=openid profile email phone offline_access",
    beforeData: '{"scopes": "openid profile email"}',
    afterData: '{"scopes": "openid profile email phone offline_access"}',
    errorMsg: ""
  },
  {
    id: "LOG-0027",
    time: "2026-06-10 11:15:30",
    user: "李国强",
    userId: "U1002",
    department: "总裁办",
    module: "auth",
    actionType: "测试 SAML SSO 连接阻断",
    target: "SAML 身份服务器测试",
    targetId: "PROV_SAML",
    result: "failed",
    ip: "122.45.1.92",
    traceId: "tr-7f000001-44ab-99de",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "POST /api/v1/system/auth/PROV_SAML/test",
    beforeData: "-",
    afterData: "-",
    errorMsg: "无法获取 XML 描述符：请求 HTTPS 超时 [https://saml.haze-corp.com/metadata]"
  },
  {
    id: "LOG-0028",
    time: "2026-06-10 10:00:00",
    user: "章建华",
    userId: "U1001",
    department: "企业架构部",
    module: "settings",
    actionType: "开启系统级 Webhook 事件通知",
    target: "全局消息通知配置",
    targetId: "CH_WEBHOOK",
    result: "success",
    ip: "192.168.1.18",
    traceId: "tr-7f000001-381a-ccda",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    requestSummary: "PUT /api/v1/system/notifications/channels/CH_WEBHOOK - enabled=true",
    beforeData: '{"enabled": false}',
    afterData: '{"enabled": true}',
    errorMsg: ""
  },
  {
    id: "LOG-0029",
    time: "2026-06-10 09:12:00",
    user: "沈腾",
    userId: "U1019",
    department: "业务运营组一队",
    module: "market",
    actionType: "运行调用翻译 Tool",
    target: "高级多国语言互译助手 (RAG)",
    targetId: "SK-2015",
    result: "success",
    ip: "192.168.3.118",
    traceId: "tr-7f000001-bcfe-eefa",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "POST /api/v1/market/skills/SK-2015/run - params={'target': 'Japanese'}",
    beforeData: "-",
    afterData: '{"status": "ok"}',
    errorMsg: ""
  },
  {
    id: "LOG-0030",
    time: "2026-06-10 08:30:00",
    user: "沈腾",
    userId: "U1019",
    department: "业务运营组一队",
    module: "auth",
    actionType: "通过 OIDC SSO 系统鉴权成功",
    target: "SSO 鉴权网关",
    targetId: "PROV_OIDC",
    result: "success",
    ip: "192.168.3.118",
    traceId: "tr-7f000001-7a8f-2234",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestSummary: "GET /api/v1/auth/callback/oidc?code=***",
    beforeData: "-",
    afterData: '{"loginUser": "shenteng@haze.co"}',
    errorMsg: ""
  }
];
